---
- name: Install default modules
  apt:
    name: "{{ default_modules }}"
    update_cache: yes
    state: present
- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
- name: Upgrade all apt packages
  apt:
    upgrade: dist
    force_apt_get: yes
  become: true
- name: Get if reboot is required
  register: file
  stat: path=/var/run/reboot-required get_md5=no
- name: Show if server need restart
  debug:
    msg: need restart
  when: file.stat.exists == true
